### ISSUE TITLE
Helpwanted: How can I share my desktop with simpleh323!

### ISSUE THREAD

**Issue by rst5018** [willamowius/h323plus#10]
I used simpleh323 to share my desktop to Polycom HDX7000 but it said that:
"H.239 open error: Remote may not support feature".
I have already configure h323plus with --enable-h239!
I can't find what's wrong there. Help me please!

**Comment by willamowius** [comment]
Sharing the desktop is no different from any other H.239 video stream. You need a video device that captures the desktop, you can probably use V4L2 for that.

I'd suggest you start testing H.239 with one of the fake video sources, eg. using [callgen323](https://github.com/willamowius/callgen323) and then switch to a driver that captures the screen.

Please subscribe to the [mailinglist](https://www.h323plus.org/lists.html) for questions like these and use the issue tracker for bugs only. Thanks!
