### ISSUE TITLE
Setting PWLIBPLUGINDIR and no sound card is found anymore

### ISSUE THREAD

**Issue by kaoh** [willamowius/h323plus#18]
I compiled the audio plugins and installed them with `make install` . Then I set `PWLIBPLUGINDIR=/usr/local/lib/opal-1.27.2/codecs/audio` (I tried also a local path before `make install`- same result). When this is done all my audio devices are gone in the program.

~~~shell
 ./simph323 -P "G.726-16k{sw}" -s "Sennheiser USB headset" -l -n
simple Version 1.27.2 by H323Plus on Unix Linux (5.4.0-81-generic-x86_64)

2021/09/28 23:17:50.288	0	                (0)		Version 1.27.2 by H323Plus on Unix Linux (5.4.0-81-generic-x86_64) with PTLib (v2.10.9 (svn:0)) at 2021/9/28 23:17:50.288
Device for sound ("Sennheiser USB headset") must be one of:
  "Null Audio"
  "*.wav"
~~~

When not setting the `PWLIBPLUGINDIR` I can use all sound devices, but the plugins are missing. What is wrong?

**Comment by willamowius** [comment]
Maybe you installed a device plugin along with the codec plugins for an audio system that your Linux distro isn't using and you just need to delete it ?

But please don't use the bug tracker as a help forum.

**Comment by kaoh** [comment]
I guess, this is not a help request, but a real issue. I have created a directory `a` with a single plugin `a/speex_audio_pwplugin.so`, the `PWLIBPLUGINDIR` is pointing to directory `a` by full path. I still have no sound devices. I also compiled `simph323` statically and removed all libraries from `/usr/local/lib` again, same result. I also set `PWLIBPLUGINDIR` to some empty value or some empty directory, same result, no sound devices.

**Comment by kaoh** [comment]
I found the reason for the issue. When specifying `PWLIBPLUGINDIR` this does not only has to contain the audio codec plugins, but also the audio driver plugin. All the basic audio driver plugins are not loaded anymore from the default location anymore. A clear instruction about this behavior would be good.

Fix for this behavior:

~~~shell
cp /usr/local/lib/ptlib-2.10.9/devices/sound/* ${PWLIBPLUGINDIR}
~~~
