### ISSUE TITLE
How to add h.264 video capability in TCS?

### ISSUE THREAD

**Issue by tangshiixang** [willamowius/h323plus#20]
I downloaded h323plus source code, I have no idea how to add h.264 video capability in local capability set.

When new an endpoint, I use 'AddAllCapability(0, 0, "*")', but there're only audio capabilities in local capability set (use WireShark tool to ensure the point). I want to add h.264 video capability but I don't know how.

I have worked on this issue for days and I certainly would appreciate some helps here. Thank you.

**Comment by willamowius** [comment]
The H.264 codec is a plugin that is dynamically loaded. Make sure it is being compiled and the plugin is found by your application. You can set the plugin path with the PTLIBDIR environment variable.
