### ISSUE TITLE
callgen and simph323 H225 assert in CallCeanup

### ISSUE THREAD

**Issue by hamstie** [willamowius/h323plus#21]
Hello,
openh323 looks broken:
I got the same assert for callgen and openh323/samples/simple/simph32
Versions: 
ptlib V10.9.4 or V10.9.3 (the same)
openh323 V1.27.2
ubuntu 22.04 tls

Example called:
openh323plus/sample/simple/obj_linux_x86_64_s/simph323 -tttt -n 8.8.8.8 

It makes no different if the destination is reachable or not, after 10sec (WaitForTermination) I got the assert:

```
2022/09/30 14:06:25.037 3       transports.cxx(1065)  H323  H323Transport::Close
2022/09/30 14:06:25.037 3       transports.cxx(1210)  H323  H323Transport::CleanUpOnTermination for H225 Caller:e62c5640
2022/09/30 14:06:35.045 0           assert.cxx(114)   PWLib Assertion fail: Transport thread did not terminate, file transports.cxx, line 1211
Assertion fail: Transport thread did not terminate, file transports.cxx, line 121
```

**Comment by willamowius** [comment]
Can you please update the the latest PTLib version from Github (not the 2.10.9.4 release) and check if the problem still exists ?
I suspect you see an issue caused by glibc > 2.34.

If the issue still exists with the latest PTLib, please try on Ubuntu 20.04 which has an older glibc.

**Comment by hamstie** [comment]
Bingo, with the  latest PTLib version from Github (not the release) it works fine!!
thank you
