### ISSUE TITLE
Add lookup for ptlib-config

### ISSUE THREAD

**Issue by gkorovkin** [willamowius/h323plus#3]
Hi!

Could you please add this patch into configure.ac - it's for macports build:
-        AC_PATH_PROG(PTLIB_CONFIG, ptlib-config, , /usr/local/bin:/usr/bin)
+        AC_PATH_PROG(PTLIB_CONFIG, ptlib-config, , /usr/local/bin:/usr/bin:/opt/local/bin)

[configure.ac.diff.txt](https://github.com/willamowius/h323plus/files/1686589/configure.ac.diff.txt)

**Comment by willamowius** [comment]
Added, Thanks!
