### ISSUE TITLE
"roundTripDelayRequest" was not sent

### ISSUE THREAD

**Issue by dengliang2008** [willamowius/h323plus#30]
"roundTripDelayRequest" was not sent because of "roundTripDelayTimer > 0" in H323Connection::MonitorCallStatus function of h323.cxx.
<img width="619" alt="image" src="https://user-images.githubusercontent.com/49023241/231691219-e10d6ac5-7edc-4fdf-8104-fbaf390b4b1e.png">

**Comment by willamowius** [comment]
I think the original idea was to check that roundTripDelayrate was set before starting the timer.
Please test the patch that I just put in.

**Comment by dengliang2008** [comment]
I've seen it, it's more reasonable. :)
