### ISSUE TITLE
Calling 'H323ExtendedVideoCapability::AddAllCapabilities' twice will cause a crash

### ISSUE THREAD

**Issue by dengliang2008** [willamowius/h323plus#31]
Calling 'H323ExtendedVideoCapability::AddAllCapabilities' twice will cause crash, and 'delete childCap' should not be executed.
<img width="863" alt="image" src="https://user-images.githubusercontent.com/49023241/231693148-8da42f53-576f-41a5-8b08-4cc9150fc611.png">

**Comment by willamowius** [comment]
AddAllCapabilities() is indeed meant to be only called once.
If you want, you can provide a patch to handle calling it twice more graceful.
