### ISSUE TITLE
There is a bug in the 'Q931::SetBearerCapabilities' function

### ISSUE THREAD

**Issue by dengliang2008** [willamowius/h323plus#32]
There is a bug in the 'Q931::SetBearerCapabilities' function, when the call bandwidth is 2048kbps, data[1] should be equal to 0x18. 
And 'Q931::SetBearerTransferRate' should not be called, otherwise the call bandwidth cannot be greater than 1920kbps.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/49023241/231696568-b80c15a3-eb78-40b3-bbe4-84ada3122dd2.png">

**Comment by willamowius** [comment]
Fixed, thanks!
