### ISSUE TITLE
A crash occurs when the call is immediately hung up

### ISSUE THREAD

**Issue by Raymond-du** [willamowius/h323plus#33]
Enter the function "H323Connection::SendSignalSetup" when I call.

When I immediately hang up, enter the function "H323Connection::CleanUpOnCallEnd"
innerMutex.Wait(); Will enter the locked state, connectionState also changes to ShuttingDownConnection.
However, "signallingChannel->Connect()" is not in the locked interval
![image](https://user-images.githubusercontent.com/36786348/231981571-3b9013f6-c524-4063-926d-43373b6c8c80.png)
When connect return, the connectionState value is changed again.
innerMutex.Wait() later causes the thread to fail to exit
![image](https://user-images.githubusercontent.com/36786348/231983795-a706c27a-7133-4b8c-a3c8-f971c46d861f.png)
![image](https://user-images.githubusercontent.com/36786348/231983990-c6fb0c75-a07c-45d4-896b-82d7b5fefcc1.png)

My solution is as follows:
```
if (connectFailed) {  
  connectionState = NoConnectionActive;
  switch (signallingChannel->GetErrorNumber()) {
    case ENETUNREACH :
      reason = EndedByUnreachable;
      break;
    case ECONNREFUSED :
      reason = EndedByNoEndPoint;
      break;
    case ETIMEDOUT :
      reason = EndedByHostOffline;
      break;
    default:
       reason = EndedByConnectFail;
  }
}
```
Move this code under Lock
```
  // Lock while checking for shutting down.
  if (!Lock())
    return EndedByCallerAbort;
  else if (reason != NumCallEndReasons)
    return reason;
```
result
 ```
 // Lock while checking for shutting down.
  if (!Lock())
    return EndedByCallerAbort;
  else if (reason != NumCallEndReasons)
    return reason;
  
  // See if transport connect failed, abort if so.
  if (connectFailed) {
	connectionState = NoConnectionActive;
	switch (signallingChannel->GetErrorNumber()) {
	  case ENETUNREACH :
		reason = EndedByUnreachable;
		break;
	  case ECONNREFUSED :
		reason = EndedByNoEndPoint;
		break;
	  case ETIMEDOUT :
		reason = EndedByHostOffline;
		break;
	  default:
		 reason = EndedByConnectFail;
	}
  }
```
Adjust the location of "connectFailed" again
Please excuse my poor English!!!

**Comment by willamowius** [comment]
The locking is a tricky subject in the H323Plus code and it is not immediately obvious to me that your change doesn't break anything else.
Since we didn't get any other reports about this possible crash in the past 10 years, I will put off changing this until a patch is presented that is so simple that it can't break anything else or somebody is available to do extensive re-testing.
