### ISSUE TITLE
RTP Jitter thread consumes 100% CPU

### ISSUE THREAD

**Issue by nguyen-viet-hung** [willamowius/h323plus#7]
Dear,

I've tested with my own implemented audio capability and I found that RTP Jitter buffer consumes 100% CPU. If I change "needJitter" to FALSE in OpalMediaFormat, the CPU become normal. My Platform is CentOS 7 3.10.0-862.9.1.el7.x86_64. I attached here my sample that I modified from simple sample. Please check.
[simple_test.tar.gz](https://github.com/willamowius/h323plus/files/2222340/simple_test.tar.gz)

**Comment by willamowius** [comment]
Please send a diff to fix the issue instead of a tar archive with modified code.
